### ISSUE TITLE
抓取评论功能的问题

### ISSUE THREAD

**Issue by EricksonKop** [wenhaoliang/netease-music-spider#1]
这个抓取评论的功能实现不了啊，貌似API有变化？

**Comment by wenhaoliang** [comment]
可以把报错信息发一下吗？

**Comment by EricksonKop** [comment]
用Chrome开发者工具追踪CommentAPI页，不同页评论的encSecKey应该是不一样的，为什么您的代码里一个不变的encSecKey值可以一直用？还有就是我之前把encSecKey替换成我自己的数据就出问题了，而用你的值就可以，这个值是怎么出来的啊。。ps：你的代码没问题，主要是替换成我自己的数据就不成了

**Comment by EricksonKop** [comment]
> Traceback (most recent call last):
  File "H:/pywork/grab_music.py", line 50, in <module>
    content = json.loads(r.text)
  File "C:\Users\Administrator.USER-20160221EL\AppData\Local\Programs\Python\Python35-32\lib\json\__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Administrator.USER-20160221EL\AppData\Local\Programs\Python\Python35-32\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Administrator.USER-20160221EL\AppData\Local\Programs\Python\Python35-32\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

这是我用自己的encSecKey的报错信息

**Comment by wenhaoliang** [comment]
这个其实我也不太懂，我在写的时候是直接用这个encSecKey，然后通过传入不同的params来获取评论的，所以不太好意思~
